version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgresql
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  express-app:
    build: .
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm run dev"

volumes:
  postgres_data: